### ISSUE TITLE
Registration not visible for other users.

### ISSUE THREAD

**Issue by xardazz** [AsamK/textsecure-cli#3]
I've registered and verified new textsecure user and  I can send Messages to other TextSecure users. But when they try to send me a message they fail. Also if I register 2 different users with CLI and try to send a message from one to another - I recieve  UserNotFound Exception for the recipient.

**Comment by xardazz** [comment]
I don't know if it is linked, but if after registration and verification I try to instantiate account manager and get device info for example, I get "Error while receiving message: Authorization failed!"

```java
        accountManager = new TextSecureAccountManager(URL, TRUST_STORE, username, password, USER_AGENT);
        List<DeviceInfo> di = accountManager.getDevices();
```

**Comment by AsamK** [comment]
Probably related to this https://github.com/WhisperSystems/libtextsecure-java/issues/12
I'll have a look later

**Comment by xardazz** [comment]
Thank you for the link. really helped!

**Comment by xardazz** [comment]
Hm, still having a little problem. If I listen infinitely for new messages (keeping a connection) all is ok. But after I stop the app, after about 10 seconds official app dissallows sending encrypted messages, though TextSecure API successfully accepts them. Do you know any workaround?

**Comment by AsamK** [comment]
You can use the fetchesMessages property to mark the account as using only websockets.
To do that however you need a modified libtextsecure-java (https://github.com/AsamK/libtextsecure-java/commits/master based on WhisperSystems/libtextsecure-java#5) and the fetchMessages branch of textsecure-cli (https://github.com/AsamK/textsecure-cli/tree/feature/fetch_messages)
I just updated both to work with the latest version.

**Comment by xardazz** [comment]
Wow, was just  looking through server code, came across that  "fetchesMessages" and was thinking how to implement it - and you reply. Thank you again.

**Comment by xardazz** [comment]
Btw, today I was making  JsonAxolotlStore work with Jackson instead of Gson (as it's already a dependancy for text-secure lib). Do you need that improvement?

**Comment by AsamK** [comment]
Nice, I thought of doing that before, but didn't have the time. It would be great if you could make a PR.

**Comment by f41c0r** [comment]
look at javajens implementation of websockets on the android client as a reference? https://github.com/JavaJens/TextSecure
