### ISSUE TITLE
javax.net.ssl.SSLException: java.security.ProviderException: Could not derive key

### ISSUE THREAD

**Issue by mmhere** [AsamK/textsecure-cli#5]
i'm seeing the following exception fire when trying to register an account using:

    textsecure-cli -u nnnnnnnnnn register -v

error comes from this location in textsecure-cli's source:

    ./src/main/java/cli/Main.java:71:  System.err.println("Request verify error: " + e.getMessage());

the full line printed to the terminal including text of the error message (from deeper in the libraries somewhere) is:

    Request verify error: javax.net.ssl.SSLException: java.security.ProviderException: Could not derive key

i googled around (quite a lot, actually) and cannot find anything relevant other than greps deep inside the sun library code surrounding generation of a new secret;  this does not tell me what's happening at invocaiton of textsecure-cli.

i followed the note in textsecure-cli's README.md about using unlimited strength crypto (under Troubleshooting) but this didn't help.  (i actually never saw the specific error mentioned there regarding key size/strength.)

i am on Debian 8.  (8.2 to be precise, if my update memory serves.)

i can provide logs, etc.;  just tell me what to pull.

initially i tried openjdk-7-jdk, but could not get "./gradlew build" to work for textsecure-cli because the compileJava step complained about wanting version 1.8, so i went to the Oracle distro of Java8.  then the build command was happy.

P.S.:  I did my git clone this evening so i believe i have the latest version of textsecure-cli.

P.P.S.:  I can turn on whatever Java debug stuff may be useful (getting a stack trace might be useful?)  but i haven't done Java in a long time so i'm not sure what options i could submit to textsecure-cli to enable this sort of thing, nor what environment variables (or other stimuli) i could provide to get more info out than a simple exception message when it throws.

**Comment by AsamK** [comment]
I have no idea what's causing this error. I have java 1.8 from jessie backports running here and it works.
Also textsecure-cli doesn't actually need java 1.8, I just pushed a commit so it also compiles with java 1.7

**Comment by mmhere** [comment]
cool re the commit allowing 1.7 compilation. i'd prefer to use openjdk anyway so i'll abandon the oracle stuff for now.

thanks for the quick response too.

i'll report back to confirm closure of this issue, assuming it works.

--

(btw, any suggestions for an easy way to switch java trees? simple matter of changing JAVA_HOME, and updating /usr/bin symlinks, or just reinstall openjdk?  i know, probly a question for the search robotz...)

**Comment by AsamK** [comment]
in debian you should use the update-alternatives command, e.g.:

        update-alternatives --set java /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java

**Comment by mmhere** [comment]
thanks for the update-alternatives help, even though i know my question regarding that is sort of an aside w.r.t. the real purpose here.  i am indeed back on openjdk-7-jdk/jjre.

please note that the ./gradlew build step does now complete with your latest push;  i am able to run textsecure-cli.  but now a new error.  looks like it doesn't want to connect to the whispersystems server?  maybe?

    ./textsecure-cli -u nnnnnnnnnn register -v
    Request verify error: Bad response: 400 Bad Request

at least it's not throwing from the bowels of the encryption/key-mgmt libs.

is there additional debug i could easily switch on to help diagnose this latest issue?

**Comment by AsamK** [comment]
That server response code is sent if the specified number is not accepted by the server.
Be sure to specify the number with the country prefix, eg. +16477495XXX

**Comment by mmhere** [comment]
ah.  didn't think about globalizing the telno.  so now "register -v" has succeeded with a voice callback.  now to plug in "verify _CODE_".

**Comment by mmhere** [comment]
textsecure-cli -u '+1nnnnnnnnnn' has now succeeded, so i should be able to begin messaging.  maybe a note for the docs to ensure one uses the +1 nomenclature with north-american numbers?  should we start to populate the wiki page here?  i'm happy to add my notes from Debian8/amd64 and the fact that Oracle Java8 didn't want to play nice.

**Comment by mmhere** [comment]
once again -- thanks for all your help and the quick responses.  i'm now successfully doing:

    textsecure-cli -u +1xxxxxxxxxx send -m "server status event notification" +1yyyyyyyyyy

#Yay!

**Comment by AsamK** [comment]
I've added a check at startup now, to see if the phone number is valid.
Feel free to add useful information to the wiki.

And I'll close this issue now ;)

**Comment by mmhere** [comment]
TTFN.  i agree that the issue is closed (oops!  i pinged it open by posting again.  darn).  but it will be very useful [IMHO] for other users to be able to compile your utility against Java 1.7, expeciall the free/open version.  i felt dirty momentarily engaging in that Sun (er, Oracle) stuff.  thanks again

**Comment by mmhere** [comment]
hope it's OK to reply with this here.

i just wanted to heartily thank you for this utility.  it is so much 
more useful to be able to send detailed secure messages than sending SMS 
texts, which i was doing before.

due to the sometimes sensitive nature of the information contained, i 
felt it obliged to obfuscate the info sent via SMS. now i do not have to 
do this.
